import React from 'react';
const ST={ok:'var(--fn-nominal-primary)',error:'var(--fn-critical-primary)'};
function Select({id,options,value,defaultValue,onChange,base,setF,f,dis}){
  const [open,setOpen]=React.useState(false);const [v,setV]=React.useState(value??defaultValue??options[0]);const [hi,setHi]=React.useState(Math.max(0,options.indexOf(value??defaultValue??options[0])));const ref=React.useRef(null);
  React.useEffect(()=>{if(!open)return;const h=e=>{if(ref.current&&!ref.current.contains(e.target))setOpen(false);};document.addEventListener('mousedown',h);return()=>document.removeEventListener('mousedown',h);},[open]);
  const pick=i=>{setV(options[i]);setHi(i);setOpen(false);onChange&&onChange(options[i]);};
  const key=e=>{if(e.key==='ArrowDown'){e.preventDefault();if(!open)setOpen(true);else setHi(h=>Math.min(options.length-1,h+1));}else if(e.key==='ArrowUp'){e.preventDefault();setHi(h=>Math.max(0,h-1));}else if(e.key==='Enter'||e.key===' '){e.preventDefault();open?pick(hi):setOpen(true);}else if(e.key==='Escape'){setOpen(false);}};
  return <div ref={ref} style={{position:'relative'}}>
    <button id={id} type="button" disabled={dis} aria-haspopup="listbox" aria-expanded={open} onClick={()=>setOpen(o=>!o)} onKeyDown={key} onFocus={()=>setF(true)} onBlur={()=>setF(false)} style={{...base,display:'flex',alignItems:'center',justifyContent:'space-between',gap:10,textAlign:'left',cursor:'pointer',borderColor:open||f?'var(--synapse)':base.borderColor}}><span style={{overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{v}</span><svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" style={{flex:'none',color:'var(--nevoa)',transform:open?'rotate(180deg)':'none',transition:'transform var(--t-fast)'}}><path d="M6 9l6 6 6-6"/></svg></button>
    {open&&<ul role="listbox" style={{position:'absolute',zIndex:20,left:0,right:0,top:'calc(100% + 6px)',margin:0,padding:6,listStyle:'none',background:'var(--painel)',border:'1px solid var(--line2)',borderRadius:'var(--r-sm)',boxShadow:'0 18px 50px rgba(0,0,0,.45)',maxHeight:240,overflowY:'auto'}}>{options.map((o,i)=>{const s=o===v,h=i===hi;return <li key={o} role="option" aria-selected={s} onMouseEnter={()=>setHi(i)} onMouseDown={e=>{e.preventDefault();pick(i);}} style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:10,height:34,padding:'0 10px',borderRadius:7,fontSize:13.5,cursor:'pointer',color:s||h?'var(--ink)':'var(--nevoa)',fontWeight:s?600:400,background:h?'rgba(255,255,255,.06)':'transparent'}}><span style={{overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{o}</span>{s&&<svg viewBox="0 0 24 24" width="14" height="14" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" style={{flex:'none',color:'var(--nevoa)'}}><path d="M5 12.5l4.5 4.5L19 7.5"/></svg>}</li>;})}</ul>}
  </div>;}
const IC={copy:<><rect x="9" y="9" width="11" height="11" rx="2"/><path d="M5 15V6a2 2 0 0 1 2-2h8"/></>,paste:<><rect x="6" y="4" width="12" height="17" rx="2"/><path d="M9 4h6v3H9z"/></>,clear:<path d="M7 7l10 10M17 7L7 17"/>,reveal:<><path d="M2.5 12S6 5.5 12 5.5 21.5 12 21.5 12 18 18.5 12 18.5 2.5 12 2.5 12z"/><circle cx="12" cy="12" r="2.8"/></>,hide:<><path d="M2.5 12S6 5.5 12 5.5 21.5 12 21.5 12 18 18.5 12 18.5 2.5 12 2.5 12z"/><path d="M4 20L20 4"/></>,ok:<path d="M5 12.5l4.5 4.5L19 7.5"/>};
const AL={copy:'Copiar',paste:'Colar',clear:'Limpar',reveal:'Mostrar'};
function setNative(el,v){const s=Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype,'value').set;s.call(el,v);el.dispatchEvent(new Event('input',{bubbles:true}));}
function FieldAction({a,inp,shown,setShown,iconOnly}){
  const o=typeof a==='string'?{kind:a}:a;const k=o.kind;const [done,setDone]=React.useState(false);const [h,setH]=React.useState(false);const [fv,setFv]=React.useState(false);
  const run=async()=>{const el=inp.current;if(o.onClick){o.onClick(el&&el.value);}
    try{if(k==='copy'&&el){await navigator.clipboard.writeText(el.value);flash();}
    else if(k==='paste'&&el){const t=await navigator.clipboard.readText();setNative(el,t);el.focus();flash();}
    else if(k==='clear'&&el){setNative(el,'');el.focus();}
    else if(k==='reveal'){setShown(s=>!s);}}catch(e){}};
  const flash=()=>{setDone(true);clearTimeout(run.t);run.t=setTimeout(()=>setDone(false),1600);};
  const lab=done?(k==='copy'?'Copiado':'Colado'):(k==='reveal'?(shown?'Ocultar':'Mostrar'):(o.label||AL[k]));
  const ic=done?'ok':(k==='reveal'&&shown?'hide':k);
  return <button type="button" aria-label={lab} title={iconOnly?lab:undefined} onClick={run} onMouseEnter={()=>setH(true)} onMouseLeave={()=>setH(false)} onFocus={e=>setFv(e.target.matches(':focus-visible'))} onBlur={()=>setFv(false)} style={{flex:'none',display:'inline-flex',alignItems:'center',gap:6,height:30,padding:iconOnly?'0':'0 10px',width:iconOnly?30:'auto',justifyContent:'center',border:'none',borderRadius:6,background:h?'rgba(255,255,255,.11)':'rgba(255,255,255,.055)',color:done?'var(--fn-nominal-primary)':h?'var(--ink)':'var(--nevoa)',fontFamily:'var(--fd)',fontWeight:600,fontSize:10.5,letterSpacing:'.1em',textTransform:'uppercase',cursor:'pointer',outline:fv?'2px solid var(--synapse)':'none',outlineOffset:1,transition:'background var(--t-fast),color var(--t-fast)'}}><svg viewBox="0 0 24 24" width="15" height="15" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round">{IC[ic]}</svg>{!iconOnly&&<span>{lab}</span>}</button>;}
function SubmitBtn({label,dis}){const [h,setH]=React.useState(false);const [fv,setFv]=React.useState(false);
  return <button type="submit" aria-label={label} title={label} disabled={dis} onMouseEnter={()=>setH(true)} onMouseLeave={()=>setH(false)} onFocus={e=>setFv(e.target.matches(':focus-visible'))} onBlur={()=>setFv(false)} style={{flex:'none',display:'inline-flex',alignItems:'center',justifyContent:'center',width:34,height:34,padding:0,border:'none',borderRadius:6,background:'var(--synapse)',color:'var(--cortex)',cursor:'pointer',outline:fv?'2px solid var(--ink)':'none',outlineOffset:2,boxShadow:h?'0 6px 20px rgba(206,220,0,.22)':'none',transition:'box-shadow var(--t-fast)'}}><svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M5 12h14M13 6l6 6-6 6"/></svg></button>;}
export function Field({label,type='text',hint,state='default',options=[],rows=3,id,style,actions,iconOnly=true,submit,...rest}){
  const [f,setF]=React.useState(false);const dis=state==='disabled';
  const border=f?'var(--synapse)':ST[state]?ST[state]:'var(--line2)';
  const base={width:'100%',boxSizing:'border-box',background:f?'rgba(206,220,0,.04)':'rgba(255,255,255,.05)',border:'1px solid '+border,borderRadius:'var(--r-sm)',padding:'10px 12px',color:'var(--ink)',fontFamily:'var(--f)',fontSize:15,lineHeight:1.5,outline:'none',transition:'border-color var(--t-fast),background var(--t-fast)',opacity:dis?.4:1,pointerEvents:dis?'none':'auto'};
  const inp=React.useRef(null);const [shown,setShown]=React.useState(false);
  const ev={id,disabled:dis,onFocus:()=>setF(true),onBlur:()=>setF(false),...rest};
  const ctl=type==='select'?<Select id={id} options={options} value={rest.value} defaultValue={rest.defaultValue} onChange={rest.onChange} base={base} setF={setF} f={f} dis={dis}/>:type==='textarea'?<textarea rows={rows} {...ev} style={{...base,resize:'vertical'}}></textarea>:submit?<form onSubmit={e=>{e.preventDefault();const o=typeof submit==='object'?submit:{};o.onSubmit&&o.onSubmit(inp.current&&inp.current.value);}} style={{...base,display:'flex',alignItems:'center',gap:6,padding:'4px 4px 4px 12px',margin:0}}><input ref={inp} type={type} {...ev} style={{flex:1,minWidth:0,background:'transparent',border:'none',outline:'none',padding:'6px 0',color:'inherit',font:'inherit',lineHeight:1.5}}/><SubmitBtn label={(typeof submit==='object'&&submit.label)||'Enviar'} dis={dis}/></form>:actions&&actions.length?<div style={{...base,display:'flex',alignItems:'center',gap:4,padding:'4px 4px 4px 12px'}}><input ref={inp} type={type==='password'&&shown?'text':type} {...ev} style={{flex:1,minWidth:0,background:'transparent',border:'none',outline:'none',padding:'6px 0',color:'inherit',font:'inherit',lineHeight:1.5}}/>{actions.map((a,i)=><React.Fragment key={i}><FieldAction a={a} inp={inp} shown={shown} setShown={setShown} iconOnly={iconOnly}/></React.Fragment>)}</div>:<input type={type} {...ev} style={base}/>;
  return <div style={{display:'flex',flexDirection:'column',gap:7,...style}}><label htmlFor={id} style={{fontFamily:'var(--fd)',fontWeight:600,fontSize:10.5,letterSpacing:'.12em',textTransform:'uppercase',color:'var(--nevoa)'}}>{label}</label>{ctl}{hint&&<p style={{margin:0,fontSize:11.5,lineHeight:1.45,color:ST[state]||'var(--grafite)'}}>{hint}</p>}</div>;
}
