import React from 'react';
const Box=({on})=><span style={{width:14,height:14,flex:'none',borderRadius:3,border:'1px solid '+(on?'var(--ink)':'var(--line2)'),background:on?'var(--ink)':'transparent',display:'flex',alignItems:'center',justifyContent:'center'}}>{on&&<svg viewBox="0 0 24 24" width="11" height="11" fill="none" stroke="#050807" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"><path d="M5 12.5l4.5 4.5L19 7.5"/></svg>}</span>;
function Group({g,sel,toggle,clear}){const [open,setOpen]=React.useState(false);const ref=React.useRef(null);const n=sel.length;
  React.useEffect(()=>{if(!open)return;const h=e=>{if(ref.current&&!ref.current.contains(e.target))setOpen(false);};document.addEventListener('mousedown',h);return()=>document.removeEventListener('mousedown',h);},[open]);
  return <div ref={ref} style={{position:'relative'}}>
    <button type="button" aria-haspopup="listbox" aria-expanded={open} onClick={()=>setOpen(o=>!o)} style={{display:'inline-flex',alignItems:'center',gap:8,height:32,padding:'0 10px 0 12px',borderRadius:8,border:'1px solid '+(open||n?'var(--line2)':'var(--line)'),background:n?'rgba(255,255,255,.07)':'rgba(255,255,255,.02)',color:n?'var(--ink)':'var(--nevoa)',fontFamily:'var(--f)',fontSize:12.5,fontWeight:n?600:500,cursor:'pointer'}}>{g.label}{n>0&&<span style={{fontFamily:'var(--fm)',fontSize:10,lineHeight:'16px',padding:'0 5px',borderRadius:4,background:'var(--ink)',color:'#050807'}}>{n}</span>}<svg viewBox="0 0 24 24" width="14" height="14" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" style={{color:'var(--grafite)',transform:open?'rotate(180deg)':'none',transition:'transform var(--t-fast)'}}><path d="M6 9l6 6 6-6"/></svg></button>
    {open&&<div role="listbox" aria-multiselectable="true" style={{position:'absolute',zIndex:20,left:0,top:'calc(100% + 6px)',minWidth:220,padding:6,background:'var(--painel)',border:'1px solid var(--line2)',borderRadius:'var(--r-sm)',boxShadow:'0 18px 50px rgba(0,0,0,.45)'}}>
      {g.options.map(o=>{const on=sel.includes(o);return <div key={o} role="option" aria-selected={on} onClick={()=>toggle(o)} style={{display:'flex',alignItems:'center',gap:10,height:34,padding:'0 10px',borderRadius:7,fontSize:13.5,cursor:'pointer',color:on?'var(--ink)':'var(--nevoa)'}} onMouseEnter={e=>e.currentTarget.style.background='rgba(255,255,255,.06)'} onMouseLeave={e=>e.currentTarget.style.background='transparent'}><Box on={on}/>{o}</div>;})}
      <div style={{height:1,background:'var(--line)',margin:'6px 4px'}}></div>
      <div style={{display:'flex',justifyContent:'space-between',padding:'2px 4px'}}><button type="button" onClick={clear} style={{border:'none',background:'none',cursor:'pointer',fontFamily:'var(--f)',fontSize:12.5,color:'var(--nevoa)',padding:'6px'}}>Limpar</button><button type="button" onClick={()=>setOpen(false)} style={{border:'none',borderRadius:7,cursor:'pointer',fontFamily:'var(--fd)',fontWeight:600,fontSize:12,background:'var(--synapse)',color:'var(--cortex)',padding:'6px 12px'}}>Aplicar</button></div>
    </div>}
  </div>;}
export function FilterBar({filters=[],count,onChange}){
  const [s,setS]=React.useState(()=>Object.fromEntries(filters.map(f=>[f.label,f.selected||[]])));
  const up=n=>{setS(n);onChange&&onChange(n);};
  const toggle=(l,o)=>up({...s,[l]:s[l].includes(o)?s[l].filter(x=>x!==o):[...s[l],o]});
  const active=filters.flatMap(f=>s[f.label].map(o=>[f.label,o]));
  return <div style={{display:'flex',flexDirection:'column',gap:10}}>
    <div style={{display:'flex',alignItems:'center',gap:8,flexWrap:'wrap'}}>{filters.map(f=><Group key={f.label} g={f} sel={s[f.label]} toggle={o=>toggle(f.label,o)} clear={()=>up({...s,[f.label]:[]})}/>)}{count!=null&&<span style={{marginLeft:'auto',fontSize:12.5,color:'var(--grafite)'}}><span style={{fontFamily:'var(--fm)',color:'var(--nevoa)'}}>{count}</span> resultados</span>}</div>
    {active.length>0&&<div style={{display:'flex',alignItems:'center',gap:6,flexWrap:'wrap'}}>{active.map(([l,o])=><span key={l+o} style={{display:'inline-flex',alignItems:'center',gap:6,height:24,padding:'0 4px 0 9px',borderRadius:6,border:'1px solid var(--line2)',background:'rgba(255,255,255,.04)',fontSize:12,color:'var(--ink)'}}><span style={{color:'var(--grafite)'}}>{l}:</span>{o}<button type="button" aria-label={'Remover '+o} onClick={()=>toggle(l,o)} style={{width:18,height:18,border:'none',borderRadius:4,background:'transparent',color:'var(--nevoa)',cursor:'pointer',fontSize:13,lineHeight:1}}>×</button></span>)}<button type="button" onClick={()=>up(Object.fromEntries(filters.map(f=>[f.label,[]])))} style={{border:'none',background:'none',cursor:'pointer',fontFamily:'var(--f)',fontSize:12,color:'var(--nevoa)',textDecoration:'underline',textUnderlineOffset:3}}>Limpar filtros</button></div>}
  </div>;}
