import React from 'react';
const Ic=({d,s=20})=><svg viewBox="0 0 24 24" width={s} height={s} fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" style={{flex:'none'}}><path d={d}/></svg>;
const lab={fontFamily:'var(--fd)',fontWeight:600,letterSpacing:'.14em',textTransform:'uppercase'};
export function MobileSiteMenu({links=[],active=0,langs=['EN','PT','FR'],lang='PT',footer=[],open:o0=false,eyebrow,children}){const base=(typeof window!=='undefined'&&window.NRO_ASSET_BASE)||'';
  const [open,setOpen]=React.useState(o0);const [l,setL]=React.useState(lang);const [a,setA]=React.useState(active);
  return <div style={{position:'relative',width:'100%',height:'100%',display:'flex',flexDirection:'column',overflow:'hidden',background:'radial-gradient(120% 70% at 70% -10%,var(--glow,#081511) 0%,var(--void) 60%)',color:'var(--ink)',fontFamily:'var(--f)'}}>
    <header style={{flex:'none',position:'relative',zIndex:2,margin:'14px 14px 0',height:62,padding:'0 8px 0 16px',display:'flex',alignItems:'center',gap:10,border:'1px solid var(--line)',borderRadius:16,background:'var(--glass)',backdropFilter:'var(--blur-glass)',WebkitBackdropFilter:'var(--blur-glass)'}}>
      <img src={base+'assets/logo-imagotipo-white.png'} alt="NeuroDynamics" style={{height:17,width:'auto',display:'block',marginRight:'auto'}}/>
      {open&&<div role="group" aria-label="Idioma" style={{display:'flex',gap:1,padding:2,border:'1px solid var(--line)',borderRadius:8}}>{langs.map(x=><button key={x} onClick={()=>setL(x)} style={{height:24,minWidth:28,padding:'0 4px',border:'none',borderRadius:6,background:x===l?'rgba(255,255,255,.08)':'transparent',color:x===l?'var(--ink)':'var(--grafite)',fontFamily:'var(--fd)',fontWeight:600,fontSize:10,letterSpacing:'.06em',cursor:'pointer'}}>{x}</button>)}</div>}
      <button aria-label={open?'Fechar menu':'Abrir menu'} aria-expanded={open} onClick={()=>setOpen(v=>!v)} style={{width:46,height:46,borderRadius:12,border:'1px solid var(--line2)',background:'transparent',color:'var(--ink)',display:'flex',alignItems:'center',justifyContent:'center',cursor:'pointer'}}><Ic d={open?'M6 6l12 12M18 6 6 18':'M4 8h16M4 16h16'} s={22}/></button>
    </header>
    {open?<div style={{flex:1,minHeight:0,display:'flex',flexDirection:'column',padding:'0 24px 28px'}}>
      <nav style={{margin:0,borderTop:'1px solid var(--line)'}}>{links.map((x,i)=><a key={i} href="#" onClick={e=>{e.preventDefault();setA(i)}} style={{display:'flex',alignItems:'baseline',gap:22,minHeight:76,padding:'0 4px',borderBottom:'1px solid var(--line)',textDecoration:'none',alignItems:'center'}}><span style={{fontFamily:'var(--fm)',fontSize:12,color:'var(--grafite)',width:22}}>{String(i+1).padStart(2,'0')}</span><span style={{fontFamily:'var(--fd)',fontWeight:600,fontSize:32,letterSpacing:'-.02em',color:i===a?'var(--ink)':'var(--nevoa)'}}>{x}</span>{i===a&&<span style={{marginLeft:'auto',width:8,height:8,background:'var(--synapse)'}}></span>}</a>)}</nav>
      <div style={{marginTop:'auto',paddingTop:40,display:'flex',flexDirection:'column',gap:14}}>{footer.map((x,i)=><span key={i} style={{...lab,fontSize:11.5,color:'var(--nevoa)'}}>{x}</span>)}</div>
    </div>:<div style={{flex:1,minHeight:0,overflow:'hidden',padding:'0 24px'}}>{eyebrow&&<div style={{display:'flex',alignItems:'flex-start',gap:12,marginTop:56}}><span style={{width:9,height:9,marginTop:3,background:'var(--synapse)',flex:'none'}}></span><span style={{...lab,fontSize:11.5,lineHeight:1.6,color:'var(--nevoa)'}}>{eyebrow}</span></div>}{children}</div>}
  </div>;}
